"""HTML reporter for CloudGuard scan results."""

from __future__ import annotations

import html
from typing import Any

from cloudguard import __version__
from cloudguard.core.models import ScanResult

SEVERITY_COLORS = {
    "CRITICAL": "#dc2626",
    "HIGH": "#ea580c",
    "MEDIUM": "#ca8a04",
    "LOW": "#2563eb",
    "INFO": "#6b7280",
}


class HTMLReporter:
    """Generate a standalone HTML report from scan results."""

    def generate(self, result: ScanResult) -> str:
        summary = result.summary
        findings_html = self._build_findings_table(result)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>CloudGuard Scan Report — {result.scan_id[:8]}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; background: #0f172a; color: #e2e8f0; }}
  h1, h2 {{ color: #38bdf8; }}
  .summary {{ display: grid; grid-template-columns: repeat(5, 1fr); gap: 12px; margin: 20px 0; }}
  .summary-card {{ background: #1e293b; border-radius: 8px; padding: 16px; text-align: center; }}
  .summary-card .count {{ font-size: 2em; font-weight: bold; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
  th {{ background: #1e293b; padding: 12px; text-align: left; border-bottom: 2px solid #334155; }}
  td {{ padding: 10px 12px; border-bottom: 1px solid #1e293b; }}
  tr:hover {{ background: #1e293b; }}
  .severity {{ padding: 4px 10px; border-radius: 4px; font-weight: bold; font-size: 0.85em; color: white; }}
  .meta {{ color: #94a3b8; font-size: 0.9em; margin: 8px 0; }}
  footer {{ margin-top: 40px; color: #64748b; font-size: 0.85em; text-align: center; }}
</style>
</head>
<body>
<h1>🔒 CloudGuard Scan Report</h1>
<div class="meta">
  Scan ID: {result.scan_id} &bull; Account: {result.account_id} &bull; Region: {result.region} &bull; Duration: {result.scan_duration_seconds}s
</div>

<h2>Summary</h2>
<div class="summary">
  <div class="summary-card"><div class="count" style="color:#dc2626">{summary.get('CRITICAL',0)}</div>Critical</div>
  <div class="summary-card"><div class="count" style="color:#ea580c">{summary.get('HIGH',0)}</div>High</div>
  <div class="summary-card"><div class="count" style="color:#ca8a04">{summary.get('MEDIUM',0)}</div>Medium</div>
  <div class="summary-card"><div class="count" style="color:#2563eb">{summary.get('LOW',0)}</div>Low</div>
  <div class="summary-card"><div class="count" style="color:#6b7280">{summary.get('INFO',0)}</div>Info</div>
</div>

<h2>Findings ({len(result.findings)})</h2>
{findings_html}

<footer>Generated by CloudGuard v{__version__}</footer>
</body>
</html>"""

    def _build_findings_table(self, result: ScanResult) -> str:
        if not result.findings:
            return "<p style='color:#22c55e;font-size:1.2em'>✅ No misconfigurations found!</p>"

        severity_order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}
        sorted_findings = sorted(
            result.findings, key=lambda f: severity_order.get(f.severity.value, 5)
        )

        rows = []
        for f in sorted_findings:
            sev = f.severity.value
            color = SEVERITY_COLORS.get(sev, "#6b7280")
            rows.append(
                f"<tr>"
                f"<td>{html.escape(f.service)}</td>"
                f"<td>{html.escape(f.resource_id)}</td>"
                f"<td>{html.escape(f.issue)}</td>"
                f"<td><span class='severity' style='background:{color}'>{sev}</span></td>"
                f"<td>{f.cvss_score:.1f}</td>"
                f"<td>{html.escape(f.mitigation[:100])}...</td>"
                f"</tr>"
            )

        return (
            "<table>"
            "<thead><tr><th>Service</th><th>Resource</th><th>Issue</th>"
            "<th>Severity</th><th>CVSS</th><th>Mitigation</th></tr></thead>"
            "<tbody>" + "\n".join(rows) + "</tbody></table>"
        )
