"""Markdown reporter for CloudGuard scan results."""

from __future__ import annotations

from cloudguard import __version__
from cloudguard.core.models import ScanResult


class MarkdownReporter:
    """Generate a Markdown report from scan results."""

    def generate(self, result: ScanResult) -> str:
        summary = result.summary
        lines = [
            f"# CloudGuard Scan Report",
            f"",
            f"**Scan ID:** `{result.scan_id}`  ",
            f"**Account:** `{result.account_id}`  ",
            f"**Region:** `{result.region}`  ",
            f"**Duration:** {result.scan_duration_seconds}s  ",
            f"**Services scanned:** {', '.join(result.services_scanned)}",
            f"",
            f"## Summary",
            f"",
            f"| Severity | Count |",
            f"|----------|-------|",
            f"| 🔴 CRITICAL | {summary.get('CRITICAL', 0)} |",
            f"| 🟠 HIGH | {summary.get('HIGH', 0)} |",
            f"| 🟡 MEDIUM | {summary.get('MEDIUM', 0)} |",
            f"| 🔵 LOW | {summary.get('LOW', 0)} |",
            f"| ⚪ INFO | {summary.get('INFO', 0)} |",
            f"| **Total** | **{len(result.findings)}** |",
            f"",
        ]

        if not result.findings:
            lines.append("✅ **No misconfigurations found!**")
        else:
            lines.append("## Findings")
            lines.append("")
            lines.append("| Service | Resource | Issue | Severity | CVSS |")
            lines.append("|---------|----------|-------|----------|------|")

            severity_order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}
            sorted_findings = sorted(
                result.findings, key=lambda f: severity_order.get(f.severity.value, 5)
            )

            for f in sorted_findings:
                lines.append(
                    f"| {f.service} | `{f.resource_id}` | {f.issue} | "
                    f"**{f.severity.value}** | {f.cvss_score:.1f} |"
                )

            # Detailed findings with mitigations
            lines.append("")
            lines.append("## Remediation Details")
            lines.append("")
            for i, f in enumerate(sorted_findings, 1):
                lines.append(f"### {i}. {f.rule_id}")
                lines.append(f"")
                lines.append(f"- **Service:** {f.service}")
                lines.append(f"- **Resource:** `{f.resource_id}`")
                lines.append(f"- **Severity:** {f.severity.value} (CVSS {f.cvss_score:.1f})")
                lines.append(f"- **Issue:** {f.issue}")
                lines.append(f"")
                lines.append(f"**Mitigation:**")
                lines.append(f"```")
                lines.append(f.mitigation.strip())
                lines.append(f"```")
                lines.append(f"")

        lines.append(f"---")
        lines.append(f"*Generated by CloudGuard v{__version__}*")

        return "\n".join(lines)
